### ISSUE TITLE
Parser not available for language "pkl"

### ISSUE THREAD

**Issue by driverkt** [apple/pkl-neovim#19]
Hello. Thanks for this plugin to Neovim -- so glad it exists! 

I use [lazy.nvim](https://github.com/folke/lazy.nvim), and the pkl plugin has been broken for a while (though it did formerly function properly). 

Here is my pkl.lua currently (updated to match the one from the `README`, with the addition of the `event` stanza): 

```lua
return {
	"apple/pkl-neovim",
	lazy = true,
	ft = "pkl",
	event = {
		"BufReadPre *.pkl",
		"BufReadPre *.pcf",
		"BufReadPre PklProject",
	},
	dependencies = {
		{
			"nvim-treesitter/nvim-treesitter",
			build = function(_)
				vim.cmd("TSUpdate")
			end,
		},
		"L3MON4D3/LuaSnip",
	},
	build = function()
		vim.cmd("TSInstall! pkl")
	end,
	config = function()
		-- Set up snippets.
		require("luasnip.loaders.from_snipmate").lazy_load()
	end,
}
```

Here is what I'm seeing. 

At startup: 
```
Error detected while processing <redacted path>/nvim/init.lua:
Installation not possible: ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:87: Parser not available for language "pkl"
See https://github.com/nvim-treesitter/nvim-treesitter/#adding-parsers on how to add a new parser!
``` 

In the `:Lazy` config window: 
<img width="754" alt="image" src="https://github.com/user-attachments/assets/54b1caef-73d9-4e15-9cc9-d1fe77c88141">

**Comment by endoze** [comment]
I believe I've found the [cause](https://github.com/apple/pkl-neovim/pull/20/files) of the issue when using lazy.nvim to install this plugin. tldr is that during the build step of the plugin, you need to load the tree sitter extension so that installing the pkl parser will work correctly.
