### ISSUE TITLE
Inquiry for updating all bundled queries to latest nvim-treesitter queries

### ISSUE THREAD

**Issue by lucario387** [apple/pkl-neovim#2]
Hello to everyone reading this.

I am a member of [nvim-treesitter](https://github.com/orgs/nvim-treesitter/people), and I would like to ask for the queries to be updated. They currently do not work with current latest nvim-treesitter.

These following queries are outdated:

- indents: Reworked/Renamed since nvim-treesitter/nvim-treesitter#4524
- highlights: Renamed since nvim-treesitter/nvim-treesitter#5895

**Comment by bioball** [comment]
Hi, thanks for bringing this up. If you'd like, feel free to submit a PR to fix this.

**Comment by Senjai** [comment]
Just noting that I do think indentation does not work without this change.

**Comment by rubythulhu** [comment]
I think this is now affecting me?

```
[Neo-tree ERROR] Error opening file: vim/_editor.lua:0: nvim_exec2()..BufReadPost Autocommands for "PklProject"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 914 for language pkl
stack traceback:
	[C]: in function '_ts_parse_query'
	...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get'
	...5/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114: in function 'new'
	...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
	...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
	...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:460: in function 'start'
	...zy/opt/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
	...lazy/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
	...lazy/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...lazy/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...lazy/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
	[C]: in function 'pcall'
	.../pack/lazy/opt/neo-tree.nvim/lua/neo-tree/utils/init.lua:714: in function 'open_file'
	...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:729: in function 'open'
	...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:751: in function 'open_with_cmd'
	...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:760: in function 'open'
	...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184: in function <...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:183>
```

normally this sort of error goes away with a `:TSUpdate`, but not in this case. This seems to be after neovim and tree-sitter were recently upgraded by my homebrew. haven't noticed any other affected languages or plugins besides pkl, but this happens when opening any `.pkl` file, or even my `PklProject` that only contains `amends "pkl:project"`.

**Comment by KaminFay** [comment]
> I think this is now affecting me?
> 
> ```
> [Neo-tree ERROR] Error opening file: vim/_editor.lua:0: nvim_exec2()..BufReadPost Autocommands for "PklProject"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 914 for language pkl
> stack traceback:
> 	[C]: in function '_ts_parse_query'
> 	...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get'
> 	...5/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114: in function 'new'
> 	...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
> 	...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
> 	...r/neovim/0.9.5/share/nvim/runtime/lua/vim/treesitter.lua:460: in function 'start'
> 	...zy/opt/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
> 	...lazy/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
> 	...lazy/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
> 	...lazy/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...lazy/opt/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
> 	[C]: in function 'nvim_exec2'
> 	vim/_editor.lua: in function <vim/_editor.lua:0>
> 	[C]: in function 'pcall'
> 	.../pack/lazy/opt/neo-tree.nvim/lua/neo-tree/utils/init.lua:714: in function 'open_file'
> 	...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:729: in function 'open'
> 	...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:751: in function 'open_with_cmd'
> 	...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:760: in function 'open'
> 	...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184: in function <...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:183>
> ```
> 
> normally this sort of error goes away with a `:TSUpdate`, but not in this case. This seems to be after neovim and tree-sitter were recently upgraded by my homebrew. haven't noticed any other affected languages or plugins besides pkl, but this happens when opening any `.pkl` file, or even my `PklProject` that only contains `amends "pkl:project"`.

Looks like this is impacting my side as well. Just went through a fresh install of a few nvim distributions (LunarVim and LazyVim) which all use the lazy plugin management and they all experience the same issue.

**Comment by 7E6D4309-D2A9-4155-9D4F-287B8CDA14C1** [comment]
@bioball any updates?

**Comment by bioball** [comment]
Apologies; this fell off my radar. Will take a look today!

**Comment by bioball** [comment]
This should be fixed and working now, thanks to @jayadamsmorgan's contribution!
